# Generated by Django 5.0.2 on 2024-03-20 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('path_image', models.CharField(blank=True, default='', max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('ai_script', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('custom_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_comment', models.TextField(blank=True, default='')),
                ('star_rating', models.FloatField(default=0)),
                ('image_path', models.CharField(blank=True, default='', max_length=255)),
                ('establishment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kritikApps.establishment')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kritikApps.user')),
            ],
        ),
    ]
